# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd2eddb9afa19d68a24aad4180133bd4e6972cea3727b649eabc6a5d4870c248119a4cf9c770f0c9b7b42c39f874bfc97d1e157c80ad3e2b797ad991e4e157df

test:
  secret_key_base: 438855b4f0e1310ffcbf180c94a8e80253603704a1cf1e0d3baa1e48b571a4c4a6bb0f4903ae7a5187024de4b1745ddbb299a69b2b7fd4b30af1390c242f3b93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
